### ISSUE TITLE
Stuttgart: Use REST-API instead of scraping

### ISSUE THREAD

**Issue by wiomoc** [cvzi/mensahd#2]
http://sws.maxmanager.xyz/extern/mensa_stuttgart-mitte.json
http://sws.maxmanager.xyz/extern/mensa_stuttgart-vaihingen.json

**Comment by cvzi** [comment]
Thank you, I'll check it out

-
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

**Comment by cvzi** [comment]
It looks like the data is almost identical except for some salad dishes. That trade off seems ok.
