### ISSUE TITLE
Studierendenwerk Hamburg menu page very similar to Köln - please add

### ISSUE THREAD

**Issue by CHirch** [cvzi/mensahd#25]
Hamburg currently is a blind spot on openmensa.org. To me it seems like Hamburg uses the same menu page as Köln does. The parameters in the URL, the filters and the header and footer look quite similar.
Unfortunately my Python skills are very low but perhaps someone can adjust the script for Hamburg.
Here's a link to a menu page of Hamburg: https://www.stwhh.de/speiseplan/?l=137&t=next_day
Thanks in advance!

**Comment by CHirch** [comment]
Excellent! Thank you!

**Comment by cvzi** [comment]
The only problem is that now the locations are duplicated. I'll ask one of the maintainers if they can deactivate the ones from the old parser.
