### ISSUE TITLE
Data is not forwarded to openmensa.org

### ISSUE THREAD

**Issue by tomkoenecke** [cvzi/mensahd#28]
Parsed data for Stuttgart Vaihingen show up here in the repository, but `openmensa.org` doesn't show the updated information.

**Comment by q-wertz** [comment]
Same with Stuttgart Mitte. The information for yesterday came at some point (very late) but today and the following days are also still missing.

**Comment by cvzi** [comment]
The data from Ulm parser was also not fetched by openmensa.org. It should have been fetched at the same time as Stuttgart.

I clicked the button on [openmensa.org](https://openmensa.org) on each canteen to manually trigger fetching the feeds and it worked and updated the meals.

**Comment by tomkoenecke** [comment]
Maybe this has something to do with the easter holidays?
I remember something similar happening over the christmas holidays

**Comment by cvzi** [comment]
I just found out that I can look at the times the feed was fetched when I open the canteen on openmensa.org and click on the letter-symbol next to the feed 😂

> for yesterday came at some point (very late)

It looked like this for Vaihingen:
```
12. April, 11:30 Uhr	Veränderung		(full-feed)
12. April, 12:01 Uhr	Veränderung		(today-feed)
12. April, 13:01 Uhr	Keine Veränderung	(today-feed)
12. April, 14:01 Uhr	Keine Veränderung	(today-feed)
12. April, 15:01 Uhr	Keine Veränderung	(today-feed)
12. April, 16:01 Uhr	Keine Veränderung	(today-feed)

```

...and it will look similar today.

The update times in the metadata of the stuttgart feeds is set to
full-feed: 9:30
today-feed: 10:00-14:00 (every hour)

I assumed it would be local time, but apparently openmensa uses GMT+0 to schedule fetching the feeds. I don't know if that was always the case or if it has changed?

> Maybe this has something to do with the easter holidays? I remember something similar happening over the christmas holidays

Yes, the Vaihingen canteen didn't add the meals to the website as timely as usual. It looks like the meals for Tuesday were only added to the website on Tuesday morning. Normally the meals for the next week would have already been available and fetched the week before. So it wouldn't have been obvious that the data was outdated.

**Comment by tomkoenecke** [comment]
Cool, thanks for checking! Would you be able to move the fetch times forward for the future?
