### ISSUE TITLE
New Mensa Stuttgart

### ISSUE THREAD

**Issue by q-wertz** [cvzi/mensahd#5]
In Stuttgart the new "Mensa Central" has been opened. Is it possible to add it?

https://www.studierendenwerk-stuttgart.de/essen/speiseplan

**Comment by cvzi** [comment]
Thanks, I will add it

**Comment by cvzi** [comment]
There is an endpoint at https://sws.maxmanager.xyz/extern/mensa_central.json but it doesn't list all the dishes 😐

**Comment by q-wertz** [comment]
Thanks for taking care :blush:

**Comment by q-wertz** [comment]
I think the missing dishes are the one they prepare on their own. They offer self-made noodles now and these are the one that are not listed on maxmanager. Maybe this helps. :sweat_smile:

**Comment by cvzi** [comment]
For now I switched back to the old parser which extracts the dishes from the studierendenwerk-stuttgart.de website. 

The old parser seems to still work fine, at least for the two canteens that are currently open.

**Comment by q-wertz** [comment]
For me it works like a charm. Thank you very much :)
